In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Variable initialization
epoch = 10000 #Setting training iterations
lr = 0.35 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [3]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )
print(f'wh:{wh}\n')
print(f'bh:{bh}\n')
print(f'wout:{wout}\n')
print(f'bout:{bout}')

wh:[[0.19112325 0.71150467 0.7641689 ]
 [0.69490677 0.29158504 0.47921311]
 [0.66101282 0.72514005 0.05674668]
 [0.4181571  0.45961475 0.49759719]]

bh:[[0.05637318 0.6457066  0.72959717]]

wout:[[0.51823023]
 [0.62565809]
 [0.9014043 ]]

bout:[[0.38856817]]


In [4]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.w = None
    
    def forward(self, x, w):
        self.x = x
        self.w = w
        out = np.dot(self.x, self.w)
        return out
    
    def backward(self, dout):
        dx = dout * self.w
        dw = dout * self.x
        
        return dw, dx

class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, b):
        out = x + b
        return out
    
    def backward(self, out):
        dx = out * 1
        db = out * 1
        return dx, db

class Sigmoid:
    def __init__(self):
        self.out = None
    
    def forward(self, x):
        out = 1/(1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx
        

In [5]:
mul_Layer1 = MulLayer()
add_Layer1 = AddLayer()
sigmoid_Layer1 = Sigmoid()
mul_Layer2 = MulLayer()
add_Layer2 = AddLayer()
sigmoid_Layer2 = Sigmoid()

# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [6]:
# for i in  range ( epoch ):
cnt = 0
while (1):
    cnt += 1
    #Forward Propogation
    x1_w1 = mul_Layer1.forward(X, wh)
    x1_w1_b1 = add_Layer1.forward(x1_w1, bh)
    layer1_out = sigmoid_Layer1.forward(x1_w1_b1)
    
    # 寫出output Layer
    x2_w2 = mul_Layer2.forward(layer1_out, wout)
    x2_w2_b2 = add_Layer2.forward(x2_w2, bout)
    output = sigmoid_Layer2.forward(x2_w2_b2)
    
    # (BP)
    dout = y - output
    dsigmoid2 = sigmoid_Layer2.backward(dout)
    dx2_w2, db2 = add_Layer2.backward(dsigmoid2)
    dx2, dw2 = mul_Layer2.backward(dx2_w2)
    
    # Update law
    wout = wout + lr * dw2
    bout = bout + lr * db2
    
    if np.std(y-output, ddof = 1) <= 0.003:
        break

print(f"output of Forward Propogation:\n{format(output)}\n")
print(f"wout of Backpropagation:\n{format(wout)}\n")
print(f"bout of Backpropagation:\n{format(bout)}\n")
print(f"Conut: {cnt}\n")
print(f"MSE:{np.std(y-output, ddof = 1)}")

output of Forward Propogation:
[[0.99866325]
 [0.99880738]
 [0.00392997]]

wout of Backpropagation:
[[2.85919493e+00]
 [2.78978153e+00]
 [2.72466266e-05]]

bout of Backpropagation:
[[ 2.0978173 ]
 [ 1.88458585]
 [-9.95344874]]

Conut: 172358

MSE:0.0029999982434756513
